[package]
name = "orbsim"
version = "0.2.0"
authors = ["sebmarton"]
edition = "2018"

[dependencies]
piston_window = "0.116.0"
serde = {version = "1.0", features = ["derive"]}
serde_json = "1.0"
plotlib = "0.5.1"